# This rule is not used by the project solr-collections-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to solrcollections.solr.sis.uw.edu resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: solr-collections-operator
    app.kubernetes.io/managed-by: kustomize
  name: solrcollectionset-viewer-role
rules:
- apiGroups:
  - solrcollections.solr.sis.uw.edu
  resources:
  - solrcollectionsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - solrcollections.solr.sis.uw.edu
  resources:
  - solrcollectionsets/status
  verbs:
  - get
