name: Build

on:
  push:
    branches:
      - development
      - evaluation
      - patch
      - master

env:
  COLLECTIVE: planning
  _ARTIFACT: solr-collections-operator


jobs:
  build:
    name: Build, Test, Deploy Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v4

      - name: Get Version
        run: |
          export _VERSION=`cat VERSION`
          echo "_VERSION=$_VERSION" >> $GITHUB_ENV

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Run linter
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.5.0

      - name: Running Tests
        run: |
          go mod tidy
          make test
          
      - name: Build and Publish Docker Image
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
          make docker-build docker-push IMG=ghcr.io/${{github.repository}}/$_ARTIFACT:$_VERSION
