name: Tests

on:
  push:
    branches:
      - development
      - evaluation
      - patch
      - master

jobs:
  build:
    name: Build, Test, Release
    runs-on: ubuntu-latest
    permissions:
      # This is for the helm publish ...
      contents: write
    steps:
      - name: Clone the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Version
        run: |
          export _VERSION=`cat VERSION`
          echo "_VERSION=$_VERSION" >> $GITHUB_ENV

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Run linter
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.5.0

      - name: Running Tests
        run: |
          go mod tidy
          make test

      - name: Install Kubebuilder
        run: |
          KUBEBUILDER_VERSION=v4.10.1
          curl -L -o kubebuilder "https://github.com/kubernetes-sigs/kubebuilder/releases/download/${KUBEBUILDER_VERSION}/kubebuilder_linux_amd64"
          chmod +x kubebuilder

      - name: Verify Kubebuilder
        run: ./kubebuilder version

      - name: Make Operator Installer
        run: |
          make build-installer IMG=ghcr.io/uw-it-sis/solr-collections-operator/solr-collections-operator:v${_VERSION}

      - name: Create Helm Chart
        run: | 
          ./kubebuilder edit --plugins=helm/v2-alpha --output-dir=charts

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      # https://github.com/marketplace/actions/helm-chart-releaser
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"